-- ════════════════════════════════════════════════════════════════════════════
-- Shared/Constants.lua
-- System-wide constants, default configurations, and state schemas
-- ════════════════════════════════════════════════════════════════════════════

local UserInputService = game:GetService("UserInputService")

local Constants = {
	APP_NAME = "B0Xaz Universal",
	VERSION = "2.0.0",
	FOLDER = "B0XazUniversal",
	CONFIG_EXT = ".json",
	AUTOLOAD_FILE = "_autoload",

	IS_MOBILE = UserInputService.TouchEnabled and not UserInputService.KeyboardEnabled,

	UI = {
		WIDTH = 660,
		HEIGHT = 460,
		TITLE_HEIGHT = 28,
		TAB_HEIGHT = 26,
		NOTIFY_DEFAULT_TIME = 3.5,
	},

	TIER = {
		NONE = 0,
		ENTRY = 1,
		NORMAL = 2,
		FULL = 3,
	},

	TIER_NAMES = {
		[0] = "No Access",
		[1] = "Entry",
		[2] = "Normal",
		[3] = "Full Access",
	},

	DEFAULT_CONFIG = {
		Aimbot = {
			Enabled = false,
			UseCamera = false,
			Keybind = Enum.UserInputType.MouseButton2,
			Hitpart = "Head",
			Smoothness = 4,
			MovementMode = "Linear",
			WindStrength = 1,
			WindDamping = 0.8,
			LockMode = "Hold",
			Prediction = { Horizontal = 0, Vertical = 0 },
			TeamCheck = false,
			FriendCheck = true,
			WhitelistCheck = true,
			ForceFieldCheck = true,
			VisCheck = true,
			MaxDistance = 1000,
			ShakeIntensity = 0,
			UnlockOnDeath = true,
			BreakOnPull = false,
			MaxLockRadius = 200,
			Triggerbot = {
				Enabled = false,
				Delay = 0.05,
				TeamCheck = false,
				FriendCheck = true,
				WhitelistCheck = true,
				ForceFieldCheck = true,
				VisCheck = false,
				MaxDistance = 1000,
			},
			FOV = {
				Size = 150,
				Show = true,
				Filled = false,
				Thickness = 1,
				Sides = 64,
				Rainbow = false,
				Pulse = false,
			},
		},
		Movement = {
			Speed = 16,
			JumpPower = 50,
			InfJump = false,
			FlyEnabled = false,
			FlySpeed = 50,
			FlyKeybind = Enum.KeyCode.F,
			MobileFlyUp = false,
			MobileFlyDown = false,
			SprintEnabled = false,
			SprintSpeed = 30,
			CFrameSpeed = false,
			CFrameSpeedValue = 50,
		},
		ESP = {
			Enabled = false,
			Box = false,
			Name = false,
			Health = false,
			Distance = false,
			Tool = false,
			Backpack = false,
			Tracers = false,
			Skeleton = false,
			HeadDot = false,
			LookDir = false,
			TeamCheck = false,
			MaxDist = 500,
			Color = Color3.fromRGB(0, 200, 255),
			Font = "Monospace",
			Outline = true,
			AutoScaling = true,
		},
		Chams = {
			Enabled = false,
			UseTeamColor = false,
			DepthMode = "AlwaysOnTop",
			FillColor = Color3.fromRGB(0, 170, 255),
			OutlineColor = Color3.fromRGB(255, 255, 255),
		},
		Camera = { FOV = 90 },
		Visuals = { Fullbright = false },
		Extras = {
			Hitbox = { Enabled = false, Size = 10 },
			SpinBot = { Enabled = false, Speed = 20 },
			SpeedLines = false,
		},
		Performance = {
			NoTextures = false,
			LowMaterials = false,
			OptimizeTerrain = false,
			NoPostProcessing = false,
			NoShadows = false,
			NoParticles = false,
		},
		Game = {},
		Settings = {
			MenuKeybind = Enum.KeyCode.RightShift,
			IncludeSelf = false,
			UIScale = 1.0,
			ShowHotkeys = false,
			ShowFPS = false,
			ShowPing = false,
			AntiAfk = false,
			TpToMouse = false,
			Whitelist = {},
		},
	},
}

return Constants
